# Generated by Django 4.2 on 2025-11-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('estimated_hours', models.FloatField(default=0)),
                ('importance', models.IntegerField(default=5)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependencies', models.ManyToManyField(blank=True, related_name='dependent_tasks', to='tasks.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
